version: '3.9'

volumes:
  pgdata:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./32-crud/.env.prod.db
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U hello_django -d hello_django_dev"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build: ./32-crud
#    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8001
    ports:
      - 8001:8001
    env_file:
      - ./32-crud/.env.prod
    depends_on:
      - db
#  nginx:
#    build: ./nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - backend